(function(){
"use strict";
var VERSION="0.1.0",BOARD_KEY="obzue-desk-board-v1",NOTES_KEY="obzue-desk-notes-v1";
var ICONS=[{id:"binder",name:"Binder"},{id:"assistant",name:"Assistant"},{id:"notes",name:"Notes"},{id:"files",name:"Files"},{id:"audioPlayer",name:"Audio"},{id:"videoPlayer",name:"Video"},{id:"browser",name:"Zue Browser"},{id:"controlPanel",name:"Control Panel"},{id:"trash",name:"Trash"}];
var SEED={company:"ObzueAI",desk:"Binder",version:VERSION,tickets:[{id:"B-001",title:"Ship Obzue Desk v0.1",status:"done",owner:"Desk",priority:1,probe:"repo + export",evidence:"https://github.com/obzue/Obzue-Desk"},{id:"B-002",title:"Stranger completes the 60-second demo",status:"todo",owner:"Founder",priority:1,probe:"board.json downloaded",evidence:""}]};
var HELP="<!DOCTYPE html><html><body style='font-family:sans-serif;padding:24px'><h1>Obzue Desk v0.1</h1><p>Browser desk. Not a native OS.</p></body></html>";
function clone(o){return JSON.parse(JSON.stringify(o))}
function downloadJson(name,data){var b=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});var u=URL.createObjectURL(b);var a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function norm(raw){var t=(raw||"").trim();if(!t||t==="about:home")return"about:home";if(/^https?:\/\//i.test(t))return t;if(t.startsWith("www.")||(t.includes(".")&&!t.includes(" ")))return"https://"+t;return"https://duckduckgo.com/?q="+encodeURIComponent(t)}
function glyph(id){return({binder:"B",assistant:"AI",notes:"N",files:"F",audioPlayer:"A",videoPlayer:"V",browser:"Z",controlPanel:"C",trash:"T"})[id]||"*"}
function ObzueDesk(){this.apps=new Map();this.windows=new Map();this.zTop=10;this.masterVolume=1;this.trashed=[];this.clock24=true;this.boot()}
ObzueDesk.prototype.boot=async function(){await new Promise(function(r){setTimeout(r,800)});document.getElementById("boot-screen").style.display="none";var d=document.getElementById("desktop");d.hidden=false;var s=document.getElementById("version-stamp");if(s)s.textContent="v"+VERSION;var self=this;ICONS.forEach(function(i){self.apps.set(i.id,{launch:function(){self.openApp(i.id)}})});this.setupDesktop();this.setupMenus();this.setupTaskbar();this.setupListeners()};
ObzueDesk.prototype.setupDesktop=function(){var root=document.getElementById("desktop-icons");root.replaceChildren();var self=this;ICONS.filter(function(i){return self.trashed.indexOf(i.id)<0}).forEach(function(icon){var b=document.createElement("button");b.type="button";b.className="desktop-icon";b.innerHTML="<span class=glyph>"+glyph(icon.id)+"</span><span>"+icon.name+"</span>";b.onclick=function(){self.launch(icon.id)};b.oncontextmenu=function(e){e.preventDefault();e.stopPropagation();self.ctx(e.clientX,e.clientY,icon.id)};root.appendChild(b)})};
ObzueDesk.prototype.setupMenus=function(){var start=document.getElementById("start-menu");var self=this;start.innerHTML=ICONS.map(function(i){return"<button type=button class=menu-item data-app="+i.id+">"+i.name+"</button>"}).join("")+"<div class=menu-sep></div><button type=button class=menu-item data-act=about>About Desk</button>";start.onclick=function(e){var b=e.target.closest("[data-app],[data-act]");if(!b)return;if(b.dataset.app)self.launch(b.dataset.app);if(b.dataset.act==="about")self.openApp("assistant");self.hide()}};
ObzueDesk.prototype.setupTaskbar=function(){var self=this;function tick(){document.getElementById("clock").textContent=new Date().toLocaleTimeString([],{hour12:!self.clock24})}tick();setInterval(tick,1000);var box=document.getElementById("volume-slider-container");document.getElementById("volume-toggle").onclick=function(e){e.stopPropagation();box.classList.toggle("show")};document.getElementById("master-volume").oninput=function(e){self.masterVolume=Number(e.target.value)/100;if(window.Howler)Howler.volume(self.masterVolume)}};
ObzueDesk.prototype.setupListeners=function(){var self=this;document.getElementById("start-menu-button").onclick=function(e){e.stopPropagation();var m=document.getElementById("start-menu");var open=m.classList.contains("hidden");self.hide();if(open)m.classList.remove("hidden")};document.addEventListener("click",function(e){if(!e.target.closest("#start-menu,#start-menu-button"))document.getElementById("start-menu").classList.add("hidden");if(!e.target.closest("#volume-control"))document.getElementById("volume-slider-container").classList.remove("show");if(!e.target.closest("#context-menu"))document.getElementById("context-menu").classList.add("hidden")});document.addEventListener("contextmenu",function(e){if(e.target.closest(".window"))return;e.preventDefault();self.ctx(e.clientX,e.clientY,null)})};
ObzueDesk.prototype.hide=function(){document.getElementById("start-menu").classList.add("hidden");document.getElementById("context-menu").classList.add("hidden")};
ObzueDesk.prototype.ctx=function(x,y,id){var menu=document.getElementById("context-menu");var html="";if(id&&id!=="trash"){html+="<button type=button class=menu-item data-app="+id+">Open</button><button type=button class=menu-item data-trash="+id+">Trash</button>"}html+="<button type=button class=menu-item data-app=binder>Binder</button>";menu.innerHTML=html;menu.style.left=Math.min(x,innerWidth-220)+"px";menu.style.top=Math.min(y,innerHeight-180)+"px";menu.classList.remove("hidden");var self=this;menu.onclick=function(e){var b=e.target.closest("[data-app],[data-trash]");if(!b)return;if(b.dataset.app)self.launch(b.dataset.app);if(b.dataset.trash){self.trashed.push(b.dataset.trash);self.setupDesktop()}self.hide()}};
ObzueDesk.prototype.launch=function(id){var a=this.apps.get(id);if(a)a.launch()};
ObzueDesk.prototype.openApp=function(id){var map={binder:this.makeBinder,assistant:this.makeAssistant,notes:this.makeNotes,files:this.makeFiles,audioPlayer:this.makeAudio,videoPlayer:this.makeVideo,browser:this.makeBrowser,controlPanel:this.makeControls,trash:this.makeTrash};var fn=map[id];if(!fn)return;var built=fn.call(this);this.win(built.title,built.node,built.onClose,built.padless)};
ObzueDesk.prototype.win=function(title,node,onClose,padless){var id="w"+Date.now().toString(16);var el=document.createElement("div");el.className="window";var off=28+(this.windows.size%8)*18;el.style.left=off+"px";el.style.top=off+"px";el.innerHTML="<div class=window-header><h2></h2><div class=window-controls><button type=button class=win-btn data-min>–</button><button type=button class=win-btn data-close>×</button></div></div><div class=\"window-content"+(padless?" padless":"")+"\"></div>";el.querySelector("h2").textContent=title;el.querySelector(".window-content").appendChild(node);document.getElementById("windows").appendChild(el);var rec={id:id,title:title,el:el,onClose:onClose};this.windows.set(id,rec);this.bind(rec);this.focus(id);this.tasks()};
ObzueDesk.prototype.bind=function(rec){var self=this,drag=false,sx,sy,ox,oy;rec.el.addEventListener("mousedown",function(){self.focus(rec.id)});rec.el.querySelector("[data-close]").onclick=function(){self.close(rec.id)};rec.el.querySelector("[data-min]").onclick=function(){rec.el.style.display="none";self.tasks()};rec.el.querySelector(".window-header").onmousedown=function(e){if(e.target.closest("button"))return;drag=true;sx=e.clientX;sy=e.clientY;ox=rec.el.offsetLeft;oy=rec.el.offsetTop;e.preventDefault()};document.addEventListener("mousemove",function(e){if(!drag)return;rec.el.style.left=ox+(e.clientX-sx)+"px";rec.el.style.top=Math.max(0,oy+(e.clientY-sy))+"px"});document.addEventListener("mouseup",function(){drag=false})};
ObzueDesk.prototype.focus=function(id){this.zTop+=1;var rec=this.windows.get(id);if(!rec)return;rec.el.style.display="flex";rec.el.style.zIndex=String(this.zTop);this.windows.forEach(function(item){item.el.classList.toggle("focused",item.id===id)});this.tasks()};
ObzueDesk.prototype.close=function(id){var rec=this.windows.get(id);if(!rec)return;if(typeof rec.onClose==="function")rec.onClose();rec.el.remove();this.windows.delete(id);this.tasks()};
ObzueDesk.prototype.tasks=function(){var bar=document.getElementById("task-buttons");bar.replaceChildren();var self=this;this.windows.forEach(function(rec){var b=document.createElement("button");b.type="button";b.className="task-btn";b.textContent=rec.title;b.onclick=function(){if(rec.el.style.display==="none")self.focus(rec.id);else if(rec.el.classList.contains("focused"))rec.el.style.display="none";else self.focus(rec.id);self.tasks()};bar.appendChild(b)})};
ObzueDesk.prototype.loadBoard=function(){try{var raw=localStorage.getItem(BOARD_KEY);if(!raw)return clone(SEED);var d=JSON.parse(raw);return d.tickets?d:clone(SEED)}catch(e){return clone(SEED)}};
ObzueDesk.prototype.saveBoard=function(b){localStorage.setItem(BOARD_KEY,JSON.stringify(b))};
ObzueDesk.prototype.makeBinder=function(){var board=this.loadBoard();var node=document.createElement("div");node.className="stack";var list=document.createElement("div");list.className="stack";var self=this;function draw(){list.replaceChildren();board.tickets.forEach(function(t){var row=document.createElement("div");row.className="ticket-row";row.innerHTML="<strong>"+t.id+"</strong><span>"+t.title+"</span><span class=muted>"+t.status+" · "+t.owner+"</span>";var n=document.createElement("button");n.type="button";n.textContent="Advance";n.onclick=function(){var o=["todo","in_progress","in_review","done"];var i=o.indexOf(t.status);t.status=o[Math.min(o.length-1,Math.max(0,i)+1)];self.saveBoard(board);draw()};row.appendChild(n);list.appendChild(row)})}var tools=document.createElement("div");tools.className="player-tools";var inp=document.createElement("input");inp.placeholder="New ticket title";inp.style.cssText="flex:1;padding:8px";var add=document.createElement("button");add.type="button";add.textContent="Add";add.onclick=function(){var title=inp.value.trim();if(!title)return;board.tickets.push({id:"B-"+String(board.tickets.length+1).padStart(3,"0"),title:title,status:"todo",owner:"Desk",priority:2,probe:"named file",evidence:""});self.saveBoard(board);inp.value="";draw()};var exp=document.createElement("button");exp.type="button";exp.textContent="Export";exp.onclick=function(){downloadJson("board.json",board)};var imp=document.createElement("input");imp.type="file";imp.accept="application/json";imp.onchange=async function(){var f=imp.files[0];if(!f)return;try{var data=JSON.parse(await f.text());if(!Array.isArray(data.tickets))throw 0;board.tickets=data.tickets;self.saveBoard(board);draw()}catch(e){alert("Not a Binder board.")}};tools.append(inp,add,exp,imp);var note=document.createElement("p");note.className="muted";note.textContent="Binder on Desk v"+VERSION+". Export is the publish check.";node.append(note,tools,list);draw();return{title:"Binder",node:node}};
ObzueDesk.prototype.makeAssistant=function(){var n=document.createElement("div");n.className="stack";n.innerHTML="<p>Obzue Desk v"+VERSION+". Browser only. Not Corta. Not Paperclip.</p><div class=chat-log><p>Done test: Binder → Add → Export → board.json</p><p class=muted>https://github.com/obzue/Obzue-Desk</p></div>";return{title:"Assistant",node:n}};
ObzueDesk.prototype.makeNotes=function(){var n=document.createElement("div");n.innerHTML="<label>Scratch pad<textarea class=notes></textarea></label><p class=muted>localStorage only.</p>";var a=n.querySelector("textarea");a.value=localStorage.getItem(NOTES_KEY)||"";a.oninput=function(){localStorage.setItem(NOTES_KEY,a.value)};return{title:"Notes",node:n}};
ObzueDesk.prototype.makeFiles=function(){var n=document.createElement("div");n.className="stack";n.innerHTML="<p>v0.1 tray. Use Binder Export for board.json.</p><ul><li>LICENSE</li><li>README.md</li><li>MAP.md</li><li>PRIVACY.md</li></ul>";return{title:"Files",node:n}};
ObzueDesk.prototype.makeAudio=function(){var n=document.createElement("div");n.className="stack";n.innerHTML="<div class=player-tools><input type=file accept=audio/*><button type=button data-play disabled>Play</button></div><p class=muted data-s>Local audio.</p>";var sound=null,play=n.querySelector("[data-play]"),self=this;n.querySelector("input").onchange=function(e){var f=e.target.files[0];if(!f||!window.Howl)return;if(sound)sound.unload();sound=new Howl({src:[URL.createObjectURL(f)],volume:self.masterVolume});play.disabled=false;n.querySelector("[data-s]").textContent=f.name};play.onclick=function(){if(!sound)return;if(sound.playing()){sound.pause();play.textContent="Play"}else{sound.play();play.textContent="Pause"}};return{title:"Audio",node:n,onClose:function(){if(sound)sound.unload()}}};
ObzueDesk.prototype.makeVideo=function(){var n=document.createElement("div");n.className="stack";var uid="vid-"+Math.random().toString(16).slice(2);n.innerHTML="<input type=file accept=video/*><video id="+uid+" class=\"video-js vjs-default-skin\" controls playsinline></video>";var player=null,self=this;n.querySelector("input").onchange=function(e){var f=e.target.files[0];if(!f||typeof videojs!=="function")return;if(player)player.dispose();player=videojs(n.querySelector("video"),{controls:true,fluid:true,sources:[{src:URL.createObjectURL(f),type:f.type||"video/mp4"}]});player.volume(self.masterVolume)};return{title:"Video",node:n,onClose:function(){if(player)player.dispose()}}};
ObzueDesk.prototype.makeBrowser=function(){var n=document.createElement("div");n.style.cssText="display:flex;flex-direction:column;height:100%";n.innerHTML="<div class=browser-toolbar><button type=button data-home>Home</button><input type=text data-url placeholder='Search or URL'><button type=button data-go>Go</button></div><iframe class=browser-frame sandbox='allow-scripts allow-forms allow-same-origin' title='Zue Browser'></iframe>";var frame=n.querySelector("iframe"),input=n.querySelector("[data-url]");function load(raw){var u=norm(raw);if(u==="about:home"){frame.srcdoc=HELP;input.value=""}else{frame.removeAttribute("srcdoc");frame.src=u;input.value=u}}load("about:home");n.querySelector("[data-go]").onclick=function(){load(input.value)};input.onkeydown=function(e){if(e.key==="Enter")load(input.value)};n.querySelector("[data-home]").onclick=function(){load("about:home")};return{title:"Zue Browser",node:n,padless:true}};
ObzueDesk.prototype.makeControls=function(){var n=document.createElement("div");n.className="stack";n.innerHTML="<label><input type=checkbox data-clock checked> 24-hour clock</label><p class=muted>Desk v"+VERSION+" · https://github.com/obzue/Obzue-Desk</p>";var self=this;n.querySelector("[data-clock]").onchange=function(e){self.clock24=e.target.checked};return{title:"Control Panel",node:n}};
ObzueDesk.prototype.makeTrash=function(){var n=document.createElement("div");n.className="stack";var self=this;if(!this.trashed.length)n.innerHTML="<p class=muted>Trash is empty.</p>";else this.trashed.forEach(function(id){var b=document.createElement("button");b.type="button";var lab=ICONS.filter(function(i){return i.id===id})[0];b.textContent="Restore "+(lab?lab.name:id);b.onclick=function(){self.trashed=self.trashed.filter(function(x){return x!==id});self.setupDesktop()};n.appendChild(b)});return{title:"Trash",node:n}};
window.addEventListener("load",function(){window.ObzueDesk=new ObzueDesk()});
})();
